const ancientEgyptdynasties = [
  { name: "Early Dynastic Period", 
    dynasty: 1, 
    start: "5100 years ago", 
    end: "4700 years ago" },
  { name: "Early Dynastic Period", 
    dynasty: 2, 
    start: "4700 years ago", 
    end: "4500 years ago" },
  { name: "Old Kingdom", 
    dynasty: 3, 
    start: "4700 years ago", 
    end: "4100 years ago" },
  { name: "Old Kingdom", 
    dynasty: 4, 
    start: "4100 years ago", 
    end: "3900 years ago" },
  { name: "Old Kingdom", 
    dynasty: 5, 
    start: "3900 years ago",
    end: "3800 years ago" },
  { name: "Old Kingdom", 
    dynasty: 6, 
    start: "3800 years ago", 
    end: "3500 years ago" },
  { name: "First Intermediate Period", 
    dynasty: 7, 
    start: "3500 years ago", 
    end: "3300 years ago" },
  { name: "First Intermediate Period", 
    dynasty: 8, 
    start: "3300 years ago", 
    end: "3100 years ago" },
  { name: "Middle Kingdom", 
    dynasty: 9, 
    start: "3100 years ago", 
    end: "2900 years ago" },
  { name: "Middle Kingdom", 
    dynasty: 10, 
    start: "2900 years ago", 
    end: "2650 years ago" },
  { name: "Middle Kingdom", 
    dynasty: 11,
    start: "2650 years ago", 
    end: "2450 years ago" },
  { name: "Middle Kingdom", 
    dynasty: 12, 
    start: "2450 years ago", 
    end: "2050 years ago" },
  { name: "Second Intermediate Period", 
    dynasty: 13, 
    start: "2050 years ago", 
    end: "1800 years ago" },
  { name: "Second Intermediate Period", 
    dynasty: 14, 
    start: "1800 years ago", 
    end: "1700 years ago" },
  { name: "Second Intermediate Period", 
    dynasty: 15, 
    start: "1700 years ago", 
    end: "1550 years ago" },
  { name: "Second Intermediate Period", 
    dynasty: 16, 
    start: "1550 years ago", 
    end: "1500 years ago" },
  { name: "Second Intermediate Period", 
    dynasty: 17, 
    start: "1500 years ago", 
    end: "1450 years ago" },
  { name: "New Kingdom", 
    dynasty: 18, 
    start: "1450 years ago", 
    end: "1200 years ago" },
  { name: "New Kingdom", 
    dynasty: 19, 
    start: "1200 years ago", 
    end: "1050 years ago" },
  { name: "New Kingdom", 
    dynasty: 20, 
    start: "1050 years ago", 
    end: "950 years ago" },
  { name: "Third Intermediate Period", 
    dynasty: 21, 
    start: "950 years ago", 
    end: "750 years ago" },
  { name: "Third Intermediate Period", 
    dynasty: 22, 
    start: "750 years ago", 
    end: "650 years ago" },
  { name: "Third Intermediate Period",
    dynasty: 23, 
    start: "650 years ago", 
    end: "550 years ago" },
  { name: "Third Intermediate Period", 
    dynasty: 24, 
    start: "550 years ago", 
    end: "450 years ago" },
  { name: "Third Intermediate Period", 
    dynasty: 25, 
    start: "450 years ago", 
    end: "400 years ago" },
  { name: "Late Period", 
    dynasty: 26, 
    start: "400 years ago", 
    end: "350 years ago" },
  { name: "Late Period", 
    dynasty: 27, 
    start: "350 years ago", 
    end: "330 years ago" },
  { name: "Late Period", 
    dynasty: 28, 
    start: "330 years ago", 
    end: "310 years ago" },
  { name: "Late Period", 
    dynasty: 29, 
    start: "310 years ago", 
    end: "270 years ago" },
  { name: "Late Period", 
    dynasty: 30, 
    start: "270 years ago", 
    end: "225 years ago" },
  { name: "Ptolemaic Dynasty", 
    dynasty: 31, 
    start: "225 years ago", 
    end: "30 years ago" },
  { name: "Roman Egypt", 
    dynasty: 32, 
    start: "30 years ago", 
    end: "395 years ago" }
];