// This constant holds an array of notable structures built during ancient Egypt's history, 
// including pyramids, temples, and other architectural marvels, along with the dynasties they are associated with.
const ancientEgyptStructures = [
    // 1st Dynasty - Early Mastabas & Fortresses
    { dynasty: 1, ruler: "Narmer (Menes)", 
                  name: "Tomb of Narmer", 
                  notes: "Royal tomb in Umm el-Qa'ab, Abydos", 
                  coordinates: "26°11'06.0\"N 31°55'15.0\"E", 
                  yearsAgo: 5100, },
    { dynasty: 1, ruler: "Hor-Aha", 
                  name: "Tomb of Hor-Aha", 
                  notes: "Royal tomb in Abydos", 
                  coordinates: "26°11'07.0\"N 31°55'14.0\"E", 
                  yearsAgo: 5070, },
    { dynasty: 1, ruler: "Djer", 
                  name: "Tomb of Djer", 
                  notes: "Royal tomb in Abydos", 
                  coordinates: "26°11'09.0\"N 31°55'13.0\"E", 
                  yearsAgo: 5050, },
    { dynasty: 1, ruler: "Den", 
                  name: "Tomb of Den", 
                  notes: "Royal tomb in Abydos", 
                  coordinates: "26°11'10.0\"N 31°55'12.0\"E", 
                  yearsAgo: 5000, },
    { dynasty: 1, ruler: "Anedjib", 
                  name: "Tomb of Anedjib", 
                  notes: "Royal tomb in Abydos", 
                  coordinates: "26°11'11.0\"N 31°55'11.0\"E",
                  yearsAgo: 4980, },
    { dynasty: 1, ruler: "Semerkhet", 
                  name: "Tomb of Semerkhet", 
                  notes: "Royal tomb in Abydos", 
                  coordinates: "26°11'12.0\"N 31°55'10.0\"E", 
                  yearsAgo: 4950, },
    { dynasty: 1, ruler: "Qa’a", 
                  name: "Tomb of Qa’a", 
                  notes: "Royal tomb in Abydos", 
                  coordinates: "26°11'13.0\"N 31°55'09.0\"E", 
                  yearsAgo: 4920, },
    { dynasty: 1, ruler: "Khasekhemwy", 
                  name: "Shunet el-Zebib", 
                  notes: "Fortress structure in Abydos", 
                  coordinates: "26°11'15.0\"N 31°55'05.0\"E", 
                  yearsAgo: 4870, },

    // 2nd Dynasty - Mastabas & Fortresses
    { dynasty: 2, ruler: "Hotepsekhemwy", 
                  name: "Tomb of Hotepsekhemwy", 
                  notes: "Located in Saqqara", 
                  coordinates: "29°52'16.0\"N 31°12'59.0\"E", 
                  yearsAgo: 4800, },
    { dynasty: 2, ruler: "Peribsen", 
                  name: "Tomb of Peribsen", 
                  notes: "Royal tomb in Abydos", 
                  coordinates: "26°11'20.0\"N 31°55'05.0\"E", 
                  yearsAgo: 4750, },
    { dynasty: 2, ruler: "Khasekhemwy", 
                  name: "Tomb of Khasekhemwy", 
                  notes: "Royal tomb in Abydos", 
                  coordinates: "26°11'21.0\"N 31°55'04.0\"E", 
                  yearsAgo: 4700, },
    { dynasty: 2, ruler: "Unknown", 
                  name: "Hierakonpolis Fortifications", 
                  notes: "Mudbrick fortress structures", 
                  coordinates: "25°05'10.0\"N 32°46'50.0\"E", 
                  yearsAgo: 4650, },

    // 3rd Dynasty - Early Pyramid Construction
    { dynasty: 3, ruler: "Unknown", 
                  name: "Mastaba 3038", 
                  notes: "Early large tomb in Saqqara", 
                  coordinates: "29°52'30.0\"N 31°13'00.0\"E", 
                  yearsAgo: 4600, },
    { dynasty: 3, ruler: "Unknown", 
                  name: "Mastaba 3111", 
                  notes: "Large tomb in Saqqara", 
                  coordinates: "29°52'35.0\"N 31°12'55.0\"E", 
                  yearsAgo: 4570, },
    { dynasty: 3, ruler: "Unknown", 
                  name: "Mastaba 17", 
                  notes: "Located in Meidum", 
                  coordinates: "29°23'17.0\"N 31°09'25.0\"E", 
                  yearsAgo: 4550, },
    { dynasty: 3, ruler: "Djoser", 
                  name: "Pyramid of Djoser", 
                  notes: "First Step Pyramid", 
                  coordinates: "29°52'16.6\"N 31°12'59.0\"E", 
                  yearsAgo: 4600, },
    { dynasty: 3, ruler: "Sekhemkhet", 
                  name: "Buried Pyramid", 
                  notes: "Unfinished pyramid in Saqqara",
                  coordinates: "29°51'57.6\"N 31°12'46.8\"E", 
                  yearsAgo: 4570, },
    { dynasty: 3, ruler: "Khaba", 
                  name: "Layer Pyramid", 
                  notes: "Located in Zawyet el-Aryan", 
                  coordinates: "29°55'58.2\"N 31°09'40.5\"E", 
                  yearsAgo: 4550, },

    // 4th Dynasty
    { dynasty: 4, name: "Pyramid of Meidum", 
                  ruler: "Sneferu", 
                  notes: "", 
                  coordinates: "29°23'17.0\"N 31°09'25.0\"E", 
                  yearsAgo: 4600 },
    { dynasty: 4, name: "Bent Pyramid", 
                  ruler: "Sneferu", 
                  notes: "", 
                  coordinates: "29°47'25.0\"N 31°12'33.0\"E", 
                  yearsAgo: 4600 },
    { dynasty: 4, name: "Red Pyramid", 
                  ruler: "Sneferu", 
                  notes: "", 
                  coordinates: "29°48'30.0\"N 31°12'21.0\"E", 
                  yearsAgo: 4600 },
    { dynasty: 4, name: "The Great Pyramid of Giza", 
                  ruler: "Khufu", 
                  notes: "", 
                  coordinates: "29°58'45.0\"N 31°08'03.0\"E", 
                  yearsAgo: 4550 },
    { dynasty: 4, name: "Pyramid of Djedefre", 
                  ruler: "Djedefre", 
                  notes: "", 
                  coordinates: "30°01'56.0\"N 31°04'29.0\"E",
                  yearsAgo: 4500 },
    { dynasty: 4, name: "Unfinished Pyramid", 
                  ruler: "Unknown", 
                  notes: "Northern Pyramid of Zawyet el'Aryan", 
                  coordinates: "29°56'24.4\"N 31°09'05.6\"E", 
                  yearsAgo: 4500 },
    { dynasty: 4, name: "Pyramid of Khafre", 
                  ruler: "Khafre", 
                  notes: "", 
                  coordinates: "29°58'34.0\"N 31°07'51.0\"E", 
                  yearsAgo: 4500 },
    { dynasty: 4, name: "Pyramid of Menkaure", 
                  ruler: "Menkaure", 
                  notes: "", 
                  coordinates: "29°58'21.0\"N 31°07'42.0\"E", 
                  yearsAgo: 4450 },

    // 5th Dynasty
    { dynasty: 5, name: "Pyramid of Userkaf", 
                  ruler: "Userkaf", 
                  notes: "", 
                  coordinates: "29°52'25.0\"N 31°13'08.0\"E", 
                  yearsAgo: 4350 },
    { dynasty: 5, name: "Pyramid of Sahure", 
                  ruler: "Sahure", 
                  notes: "Unfinished pyramid", 
                  coordinates: "29°53'52.0\"N 31°12'12.0\"E", 
                  yearsAgo: 4300 },
    { dynasty: 5, name: "Pyramid of Neferirkare", 
                  ruler: "Neferirkare", 
                  notes: "", 
                  coordinates: "29°53'42.0\"N 31°12'09.0\"E", 
                  yearsAgo: 4250 },
    { dynasty: 5, name: "Pyramid of Neferefre", 
                  ruler: "Neferefre", 
                  notes: "",
                  coordinates: "29°53'38.0\"N 31°12'06.0\"E", 
                  yearsAgo: 4250 },
    { dynasty: 5, name: "Pyramid of North Abusir", 
                  ruler: "Unknown", 
                  notes: "Unfinished pyramid", 
                  coordinates: "29°53'55.0\"N 31°12'06.0\"E", 
                  yearsAgo: 4200 },
    { dynasty: 5, name: "Pyramid of Nyuserre", 
                  ruler: "Nyuserre", 
                  notes: "Satellite pyramids", 
                  coordinates: "29°53'44.0\"N 31°12'13.0\"E", 
                  yearsAgo: 4150 },

    // 6th Dynasty (c. 2345–2181 years ago today) – End of the Old Kingdom
    { dynasty: 6, ruler: "Teti", 
                  name: "Pyramid of Teti", 
                  notes: "", 
                  coordinates: "29°52'31.0\"N 31°13'18.0\"E", 
                  yearsAgo: 4300 },
    { dynasty: 6, ruler: "Pepi I", 
                  name: "Pyramid of Pepi I", 
                  notes: "", 
                  coordinates: "29°51'16.0\"N 31°13'08.0\"E", 
                  yearsAgo: 4200 },
    { dynasty: 6, ruler: "Pepi II", 
                  name: "Pyramid of Pepi II", 
                  notes: "", 
                  coordinates: "29°50'25.1\"N 31°12'47.9\"E", 
                  yearsAgo: 4150 },
    { dynasty: 6, ruler: "Merenre", 
                  name: "Pyramid of Merenre", 
                  notes: "", 
                  coordinates: "29°51'02.0\"N 31°12'54.0\"E", 
                  yearsAgo: 4100 },
    { dynasty: 6, ruler: "Ibi", 
                  name: "Pyramid of Ibi", 
                  notes: "", 
                  coordinates: "29°50'30.0\"N 31°13'04.0\"E", 
                  yearsAgo: 4050 },

    // 7th-10th dynasties
    // First Intermediate Period (c. 2181–2055 years ago today) – Decentralization & Chaos
    { dynasty: "Historical Context", 
      notes: "During the First Intermediate Period (7th-10th dynasties), Egypt was fragmented. Rival dynasties in Herakleopolis and Thebes fought for control until Mentuhotep II reunited Egypt around 2055 years ago today." 
    },

    // 11th Dynasty (c. 2055–1985 years ago today) – Thebes Unites Egypt
    { dynasty: 11, ruler: "Mentuhotep II", 
      notes: "Mentuhotep II defeated the Herakleopolitan kings, reunifying Egypt and establishing the Middle Kingdom.", coordinates: "" 
    },

    // 12th Dynasty (c. 1985–1800 years ago today) – Middle Kingdom Peak
    { dynasty: 12, ruler: "Amenemhat I", name: "Pyramid of Amenemhet I", notes: "Amenemhat I moved the capital to Itjtawy, strengthening Egypt’s central authority.", coordinates: "29°34'29.6\"N 31°13'31.1\"E" },
    { dynasty: 12, ruler: "Amenemhat III", name: "Pyramid of Hawara", notes: "Also known as the Labyrinth, this pyramid was built with a mudbrick core, leading to poor preservation.", coordinates: "29°16'27.0\"N 30°53'56.0\"E" },
    { dynasty: 12, ruler: "Amenemhat III", name: "Black Pyramid (Dahshur)", notes: "A failed experiment in pyramid construction, built primarily from mudbrick.", coordinates: "29°47'30.0\"N 31°13'25.0\"E" },

    //12th Dynasty → Last major pyramid builders (mudbrick, poor preservation).

    //13th Dynasty → Weak rulers, beginning of instability.
    
    //14th–17th Dynasties 
    // Second Intermediate Period → Foreign Hyksos rulers in Egypt.

    // 18th Dynasty
  { name: "Pyramid of Ahmose", dynasty: 18, ruler: "Ahmose I", notes: "", coordinates: "26°10′30.0″N 31°56′16.0″E" }
  ];
  






