
// This constant holds an array of early human civilizations, including prehistoric and early 
// historical cultures, along with their start and end times.
const earlyCivilizations = [
  { name: "Paleolithic Era", 
    civilization: 1, 
    start: "20000 years ago", 
    end: "12000 years ago" },
  { name: "Mesolithic Era", 
    civilization: 2, 
    start: "12000 years ago", 
    end: "10000 years ago" },
  { name: "Neolithic Revolution", 
    civilization: 3, 
    start: "10000 years ago", 
    end: "5000 years ago" },
  { name: "Natufian Culture", 
    civilization: 4, 
    start: "13000 years ago", 
    end: "9500 years ago" },
  { name: "Jomon Culture", 
    civilization: 5, 
    start: "15000 years ago", 
    end: "3000 years ago" },
  { name: "Clovis Culture", 
    civilization: 6, 
    start: "13000 years ago", 
    end: "11000 years ago" },
  { name: "Ancient Australasia (Aboriginal Australians)", 
    civilization: 7, 
    start: "50000 years ago", 
    end: "Present" },
  { name: "Ancient Native American Civilizations", 
    civilization: 8, 
    start: "15000 years ago", 
    end: "Present" },
  { name: "Göbekli Tepe", 
    civilization: 9, 
    start: "11500 years ago", 
    end: "10500 years ago" },
  { name: "Sumerian Civilization", 
    civilization: 10, 
    start: "5100 years ago", 
    end: "4300 years ago" },
  { name: "Egyptian Civilization", 
    civilization: 11, 
    start: "5100 years ago", 
    end: "395 years ago" },
  { name: "Indus Valley Civilization", 
    civilization: 12, 
    start: "4600 years ago", 
    end: "3900 years ago" },
  { name: "Akkadian Empire", 
    civilization: 13, 
    start: "4300 years ago", 
    end: "4100 years ago" },
  { name: "Babylonian Empire", 
    civilization: 14, 
    start: "4100 years ago", 
    end: "2500 years ago" },
  { name: "Hittite Empire", 
    civilization: 15, 
    start: "3800 years ago", 
    end: "2800 years ago" },
  { name: "Minoan Civilization", 
    civilization: 16, 
    start: "3700 years ago", 
    end: "3000 years ago" },
  { name: "Mycenaean Civilization", 
    civilization: 17, 
    start: "3500 years ago", 
    end: "3000 years ago" },
  { name: "Chinese Xia Dynasty", ¨
    civilization: 18, 
    start: "4100 years ago", 
    end: "3800 years ago" },
  { name: "Assyrian Empire", 
    civilization: 19, 
    start: "3500 years ago", 
    end: "2500 years ago" },
  { name: "Olmec Civilization", 
    civilization: 20, 
    start: "3200 years ago", 
    end: "2300 years ago" },
  { name: "Persian Empire", 
    civilization: 21, 
    start: "2700 years ago", 
    end: "1700 years ago" },
  { name: "Phoenician Civilization", 
    civilization: 22, 
    start: "3200 years ago", 
    end: "2500 years ago" },
  { name: "Ancient Greek Civilization", 
    civilization: 23, 
    start: "2800 years ago", 
    end: "2000 years ago" },
  { name: "Ancient Roman Civilization", 
    civilization: 24, 
    start: "2800 years ago", 
    end: "1600 years ago" },
  { name: "Ancient Mayan Civilization", 
    civilization: 25, 
    start: "3000 years ago", 
    end: "500 years ago" },
  { name: "Carthaginian Empire", 
    civilization: 26, 
    start: "2700 years ago", 
    end: "1700 years ago" },
];
